# GitHub Actions workflow to build and archive a resume

name: build-resume-workflow

on:
  # Trigger workflow on push or pull request events for the 'main_bendavisnc' branch
  push:
    branches: [ main_bendavisnc ]
  pull_request:
    branches: [ main_bendavisnc ]

  # Enable manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    name: Build Resume
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true  # Cache gems to speed up builds

      # Build the resume
      - name: Generate Resume
        run: make resume RESUME_TITLE="Ben Davis" RESUME_MARKDOWN="markdown/ben.md" RESUME_STYLE="less/fonts-android.less assets/fontsquirrel_roboto.css"

      # Archive the generated resume PDF
      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: out/resume.pdf
          retention-days: 7  # Keep artifact for 7 days
