# GitHub Actions workflow to build and archive a resume

name: build-resume-workflow

on:
  # Trigger workflow on push or pull request events for the 'main_bendavisnc' branch
  push:
    branches: [ main_bendavisnc ]
  pull_request:
    branches: [ main_bendavisnc ]

  # Enable manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    name: Build Resume
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v6

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true  # Cache gems to speed up builds

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      # Install less compiler
      - name: Install less compiler
        run: npm install -g less

      # Build the resume
      - name: Generate Resume
        run: personal.sh

      - name: Delete old Resume
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: latest
          assets: '*.*'
          fail-if-no-assets: false
          fail-if-no-release: false

      - name: Release new Resume
        uses: softprops/action-gh-release@v1
        with:
          files: out/resume.pdf
          tag_name: latest
        